### ISSUE TITLE
version 3.1.1 not starting

### ISSUE THREAD

**Issue by sandrokeil** [arangodb/arangodb-docker#26] opened 2016-11-19 17:57 UTC
The following error occurs if I run `docker run -e ARANGO_RANDOM_ROOT_PASSWORD=1 -d --name arangodb-instance arangodb:3.1.1`:

```
Initializing root user...Hang on...
Initializing database...Hang on...
/entrypoint.sh: line 74:    46 Terminated              arangod --server.endpoint unix:///tmp/arangodb-tmp.sock --server.authentication false --log.file /tmp/init-log --log.foreground-tty false
ArangoDB Init failed.
```

Version 3.0 and 3.1.0 are working. Any ideas?

**Comment by fceller** [comment] 2016-11-19 17:58
Will try to reproduce.

**Comment by fceller** [comment] 2016-11-19 18:38
@sandrokeil that seems to be some very strange timing problem plus a bug in 3.1 entry script, which is sometimes triggered.

I've create a fix. Could you test 

`docker run -it -e ARANGO_RANDOM_ROOT_PASSWORD=1 arangodb/arangodb:3.1.1`

before I push it to the official lib?

**Comment by sandrokeil** [comment] 2016-11-19 19:00
@fceller I've followed the instructions in readme but I can't build the image. I get a 404 error

```
Processing triggers for libc-bin (2.19-18+deb8u6) ...
Processing triggers for ca-certificates (20141019+deb8u1) ...
Updating certificates in /etc/ssl/certs... 174 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d....done.
converted 'https://www.arangodb.com/repositories/arangodb2/Debian_8.0/amd64/arangodb_@VERSION@_amd64.deb.asc' (ANSI_X3.4-1968) -> 'https://www.arangodb.com/repositories/arangodb2/Debian_8.0/amd64/arangodb_@VERSION@_amd64.deb.asc' (UTF-8)
--2016-11-19 18:59:18--  https://www.arangodb.com/repositories/arangodb2/Debian_8.0/amd64/arangodb_@VERSION@_amd64.deb.asc
Resolving www.arangodb.com (www.arangodb.com)... 85.214.140.94
Connecting to www.arangodb.com (www.arangodb.com)|85.214.140.94|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-11-19 18:59:19 ERROR 404: Not Found.

The command '/bin/sh -c apt-get update &&     apt-get install -y --no-install-recommends         libgoogle-perftools4         ca-certificates         pwgen         wget     &&     rm -rf /var/lib/apt/lists/* &&     wget ${ARANGO_SIGNATURE_URL} &&           wget ${ARANGO_PACKAGE_URL} &&             gpg --verify ${ARANGO_PACKAGE}.asc &&     dpkg -i ${ARANGO_PACKAGE} &&     sed -ri         -e 's!127\.0\.0\.1!0.0.0.0!g'         -e 's!^(file\s*=).*!\1 -!'         -e 's!^#\s*uid\s*=.*!uid = arangodb!'         -e 's!^#\s*gid\s*=.*!gid = arangodb!'         /etc/arangodb/arangod.conf     &&     apt-get purge -y --auto-remove ca-certificates wget &&     rm -f ${ARANGO_PACKAGE}*' returned a non-zero code: 8
```

**EDIT:** I've forgotten to set the version.

**Comment by fceller** [comment] 2016-11-19 19:01
@sandrokeil you should be able to just execute (without building):

docker run -it -e ARANGO_RANDOM_ROOT_PASSWORD=1 arangodb/arangodb:3.1.1

**Comment by sandrokeil** [comment] 2016-11-19 19:25
@fceller Bad news. I used `Dockerfile31.templ` but If I start the container with `docker run arangotest` I get this error:

```
touch: cannot touch '/var/lib/arangodb/_rwcheck_450b468747c4': No such file or directory
We seem to not have proper rw access to /var/lib/arangodb. Please make sure that every mounted volume has full rw access for user arangodb (uid=999(arangodb) gid=999(arangodb) groups=999(arangodb))
```

**Comment by fceller** [comment] 2016-11-19 19:26
@sandrokeil Either use

**Comment by sandrokeil** [comment] 2016-11-19 19:27
@fceller Your command works.

**Comment by fceller** [comment] 2016-11-19 19:27
@sandrokeil great. Will try to get the official build updated on Monday.

**Comment by dothebart** [comment] 2016-11-21 11:01
I've sent the PR; it will probably get merged this afternoon.

**Comment by dothebart** [comment] 2016-11-22 08:43
Merge is done, the docker library points to a working container version again.

**Closed as completed by dothebart** 2016-11-22 08:43 UTC
Labels: bug
